# import imageio.v2 as iio
hex_images = {
"Acrithia": '256px-MapAcrithiaHex.webp',
"Allod's Blight": '256px-MapAllodsBightHex.webp',
"Ash Fields": '256px-MapAshFieldsHex.webp',
"Basin Sionnach": '256px-MapBasinSionnachHex.webp',
"Callahan's Passage": '256px-MapCallahansPassageHex.webp',
"Callum's Cape": '256px-MapCallumsCapeHex.webp',
"The Clahstra": '256px-MapClahstraHex.webp',
"Clanshead Valley": '256px-MapClansheadValleyHex.webp',
"Deadlands": '256px-MapDeadlandsHex.webp',
"The Drowned Vale": '256px-MapDrownedValeHex.webp',
"Endless Shore": '256px-MapEndlessShoreHex.webp',
"Farranac Coast": '256px-MapFarranacCoastHex.webp',
"Fisherman's Row": '256px-MapFishermansRowHex.webp',
"Godcrofts": '256px-MapGodcroftsHex.png',
"Great March": '256px-MapGreatMarchHex.webp',
"The Gutter": '256px-MapGutterHex.webp',
"The Heartlands": '256px-MapHeartlandsHex.webp',
"Howl County": '256px-MapHowlCountyHex.webp',
"Kalokai": '256px-MapKalokaiHex.webp',
"King's Cage": '256px-MapKingsCageHex.webp',
"Kuura Strand": '256px-MapKuuraStrandHex.webp',
"The Linn of Mercy": '256px-MapLinnMercyHex.webp',
"Loch Mór":'256px-MapLochMorHex.webp',
"Lykos Isle": '256px-MapLykosIsleHex.png',
"Marban Hollow": '256px-MapMarbanHollowHex.webp',
"The Moors": '256px-MapMooringCountyHex.webp',
"Morgen's Crossing": '256px-MapMorgensCrossingHex.webp',
"Nevish Line": '256px-MapNevishLineHex.png',
"The Oarbreaker Isles": '256px-MapOarbreakerHex.webp',
"Olavi's Wake": '256px-MapOlavisWakeHex.webp',
"Ónyx": '256px-MapOnyxHex.webp',
"Origin": '256px-MapOriginHex.webp',
"Palantine Berm": '256px-MapPalantineBermHex.webp',
"Pari Peak": '256px-MapPariPeakHex.webp',
"Piper's Enclave": '256px-MapPipersEnclaveHex.webp',
"Reaching Trail": '256px-MapReachingTrailHex.webp',
"Reaver's Pass": '256px-MapReaversPassHex.webp',
"Red River": '256px-MapRedRiverHex.png',
"Sableport": '256px-MapSableportHex.webp',
"Shackled Chasm": '256px-MapShackledChasmHex.webp',
"Speaking Woods": '256px-MapSpeakingWoodsHex.webp',
"Stema Landing": '256px-MapStemaLandingHex.webp',
"Stlican Shelf": '256px-MapStlicanShelfHex.webp',
"Stonecradle": '256px-MapStonecradleHex.webp',
"Tempest Island": '256px-MapTempestIslandHex.webp',
"Terminus": '256px-MapTerminusHex.webp',
"The Fingers": '256px-MapTheFingersHex.webp',
"Tyrant Foothills": '256px-MapTyrantFoothillsHex.webp',
"Umbral Wildwood": '256px-MapUmbralWildwoodHex.webp',
"Viper Pit": '256px-MapViperPitHex.webp',
"Weathered Expanse": '256px-MapWeatheredExpanseHex.webp',
"Westgate": '256px-MapWestgateHex.webp',
"Wresta": '256px-MapWrestaHex.png'
}

pile_icons = {
    "Storage Depot": 'MapIconStorageFacility.png',
    "Aircraft Depot": 'MapIconAircraftDepot.webp',
    "Seaport": 'MapIconSeaport.png'
}